# Generated by Django 2.0.2 on 2020-10-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('rating', models.CharField(blank=True, max_length=3)),
                ('title', models.CharField(max_length=50)),
                ('reviewer', models.CharField(max_length=150)),
                ('review_text', models.CharField(max_length=1500)),
                ('Class', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
