# Generated by Django 2.0.2 on 2020-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20201010_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
